project_name: bomber

builds:
  - 
    binary: bomber
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: bomber
    homepage: "https://github.com/devops-kung-fu/bomber"
    tap:
      owner: devops-kung-fu
      name: homebrew-tap
    commit_author:
      name: djschleen
      email: djschleen@gmail.com

checksum:
  name_template: 'checksums.txt'

nfpms:
  - 
    maintainer: DevOps Kung Fu Mafia <admin@dkfm.io>
    description: Scans SBOMs for security vulnerabilities.
    homepage: https://github.com/devops-kung-fu/bomber
    license: MPL
    formats:
      - deb
      - rpm

